site_name: Gabriel Iturra-Bocaz
theme: 
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
    features:
        - navigation.footer


site_url: https://giturra.cl 
plugins: []
site_description: Personal Webpage of Gabriel Iturra-Bocaz
nav:
    - Home: index.md
    - Bio: bio.md
    - CV: 
        - 'Web Format': cv.md
        - 'PDF': 'documents/cv_full.pdf'
    - Blog: blog.md
copyright: Copyright &copy; 2021 - 2024 Gabriel Iturra-Bocaz
extra:
    social:
        - icon: fontawesome/brands/mastodon 

    generator: false